# Generated by Django 4.1.3 on 2023-07-16 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postleitzahl')),
                ('city_name', models.CharField(max_length=200, verbose_name='Stadt')),
                ('street_name', models.CharField(max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(max_length=10, verbose_name='Hausnummer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SwimmGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200, unique=True, verbose_name='Kurzer Name')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Beschreibung')),
                ('age_group', models.CharField(max_length=200, verbose_name='Altergruppe')),
                ('competition_participation', models.BooleanField(default=False, verbose_name='Wettkampfteilnahme')),
            ],
        ),
        migrations.CreateModel(
            name='Trainingplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Startzeit')),
                ('end_time', models.DateTimeField(verbose_name='Endzeit')),
                ('swimm_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.swimmgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='swimm_group', to='club.swimmgroup', verbose_name='Schwimmgruppe')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, verbose_name='Geburtstag')),
                ('education', models.CharField(choices=[('Keine', 'Keine'), ('Junior-Trainer', 'Junior-Trainer'), ('Trainerassistent', 'Trainerassistent'), ('C-Trainer', 'C-Trainer'), ('B-Trainer', 'B-Trainer')], max_length=200, verbose_name='Status')),
                ('expiry_date_first_aid', models.DateField(verbose_name='Ablaufdatum Erste Hilfe')),
                ('expiry_date_lifeguard', models.DateField(verbose_name='Ablaufdatum Rettungsschwimmer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='swimmgroup',
            name='main_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_trainer', to='club.trainer', verbose_name='Haupttrainer'),
        ),
        migrations.AddField(
            model_name='swimmgroup',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='trainer', to='club.trainer', verbose_name='Zusätzliche Trainer'),
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('dsv_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='DSV-ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nachname')),
                ('birth_date', models.DateField(verbose_name='Geburtstag')),
                ('attest', models.DateField(blank=True, verbose_name='Datum Attestausstellung')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.swimmgroup', verbose_name='Schwimmgruppe')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('short_name', models.CharField(max_length=100, verbose_name='Kurzer Name')),
                ('department', models.CharField(max_length=200, verbose_name='Abteilung')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.address', verbose_name='Adresse')),
            ],
        ),
    ]
