# Generated by Django 4.1.3 on 2023-07-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.IntegerField(blank=True)),
                ('number_parts', models.IntegerField(default=1)),
                ('part_distance', models.IntegerField()),
                ('part_task', models.TextField()),
                ('intensiity', models.CharField(blank=True, choices=[('loc', 'loc'), ('GA1', 'GA1'), ('GA2', 'GA2'), ('WSA', 'WSA'), ('sprint', 'sprint')], max_length=100)),
                ('tools', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.trainingplan')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
