# Generated by Django 4.1.3 on 2023-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_task_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='attest',
            field=models.DateField(blank=True, null=True, verbose_name='Datum Attestausstellung'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='tools',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
