# Generated by Django 4.1.3 on 2023-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_trainingsday_date_alter_swimmgroup_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmgroup',
            name='trainer',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainer', to='club.trainer', verbose_name='Zusätzliche Trainer'),
        ),
        migrations.AlterField(
            model_name='trainingsday',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
    ]
