# Generated by Django 4.1.3 on 2023-07-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_swimmgroup_trainer_alter_trainingsday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='total_km',
            field=models.IntegerField(default=0, verbose_name='Gesamtkilometer'),
        ),
        migrations.AlterField(
            model_name='swimmgroup',
            name='trainer',
            field=models.ManyToManyField(blank=True, related_name='trainer', to='club.trainer', verbose_name='Zusätzliche Trainer'),
        ),
    ]
