# Generated by Django 4.1.3 on 2023-07-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_trainingplan_total_km_alter_swimmgroup_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='total_km',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='total_m',
            field=models.IntegerField(default=0, verbose_name='Gesamtdistanz'),
        ),
    ]
