# Generated by Django 4.1.3 on 2023-07-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_remove_trainingplan_total_km_trainingplan_total_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimm_group', to='club.swimmgroup', verbose_name='Schwimmgruppe'),
        ),
    ]
