# Generated by Django 4.1.3 on 2023-07-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_departmentmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmanager',
            name='email',
            field=models.EmailField(default='test@test.de', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
