# Generated by Django 4.1.3 on 2023-07-29 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_departmentmanager_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.trainingplan', verbose_name='Trainingsplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='category',
            field=models.CharField(choices=[('AUSDAUER', 'Ausdauer'), ('SPRINT', 'Sprint'), ('GEMISCHT', 'Gemischt')], default='GEMISCHT', max_length=10),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.DateTimeField(verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.DateTimeField(verbose_name='Startzeit'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ANWESEND', 'a'), ('ENTSCHULDIGT', 'e'), ('UNENTSCHULDIGT', 'u')], default='ANWESEND', max_length=20)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.swimmer', verbose_name='Schwimmer')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.training', verbose_name='Training')),
            ],
        ),
    ]
