# Generated by Django 4.1.3 on 2023-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_training_training_plan_trainingplan_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ANWESEND', 'a'), ('ENTSCHULDIGT', 'e'), ('UNENTSCHULDIGT', 'u'), ('UNBEKANNT', 'x')], default='UNBEKANNT', max_length=20),
        ),
    ]
