# Generated by Django 4.1.3 on 2023-07-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
    ]
