# Generated by Django 4.1.3 on 2023-07-29 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_remove_training_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.trainingplan', verbose_name='Trainingsplan'),
        ),
    ]
