# Generated by Django 4.1.3 on 2023-08-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_training_trainer_alter_club_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.swimmgroup', verbose_name='Schwimmgruppe'),
            preserve_default=False,
        ),
    ]
