# Generated by Django 4.1.3 on 2023-08-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_trainingplan_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtstag'),
        ),
    ]
